language: python
notification:
  email: false
python:
 - "2.7"

# Command to install dependencies
install: "pip install -r testing/requirements.txt"

# Command to run tests
script: "cd testing; nosetests"
