div:
	ffmpeg -i Frames/div_%05d.png -q 1 -y div_animation.mp4
vort:
	ffmpeg -i Frames/vort_%05d.png -q 1 -y vort_animation.mp4
u:
	ffmpeg -i Frames/u_%05d.png -q 1 -y u_animation.mp4
v:
	ffmpeg -i Frames/v_%05d.png -q 1 -y v_animation.mp4
h:
	ffmpeg -i Frames/h_%05d.png -q 1 -y h_animation.mp4
video:
	ffmpeg -i Frames/%05d.png -q 1 -y animation.mp4
